image: "hseeberger/scala-sbt:8u312_1.6.2_2.13.8"

variables:
  SBT_OPTS: "-Dsbt.global.base=sbt-cache/sbtboot -Dsbt.boot.directory=sbt-cache/boot -Dsbt.coursier.home=sbt-cache/coursier"

cache:
  untracked: true
  paths:
    - "sbt-cache/boot"
    - "sbt-cache/sbtboot"
    - "sbt-cache/coursier"

get aws credentials:
  stage: .pre
  image: amazon/aws-cli:2.7.6
  script:
    - echo "CODEARTIFACT_AUTH_TOKEN=\$(aws codeartifact get-authorization-token --domain pirum-scala --domain-owner 976632135703 --query authorizationToken --output text --region eu-west-2)" >> aws.env
  artifacts:
    reports:
      dotenv: aws.env

stages:
  - lint
  - build
  - test
  - release

lint:
  stage: lint
  script:
    - sbt check

build:
  stage: build
  script:
    - sbt compile

test:
  stage: test
  script:
    - sbt test

release:
  stage: release
  rules:
    - if: \$CI_COMMIT_TAG
  script:
    - sbt 'set ThisBuild/version := "'"\${CI_COMMIT_TAG}"'"' codeArtifactPublish
